# Generated by Django 6.0.6 on 2026-06-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.TextField()),
                ('moisture', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensor_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interval_seconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_settings',
                'managed': False,
            },
        ),
    ]
