# Generated by Django 6.0.6 on 2026-07-24 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(default='新しい植物', max_length=100, verbose_name='植物名')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='栽培開始日')),
            ],
            options={
                'verbose_name': '育成植物',
                'verbose_name_plural': '育成植物',
                'db_table': 'plant',
            },
        ),
        migrations.CreateModel(
            name='PlantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='植物名')),
                ('description', models.TextField(blank=True, verbose_name='植物説明')),
                ('optimal_temperature_min', models.FloatField(blank=True, null=True, verbose_name='適正温度（下限 ℃）')),
                ('optimal_temperature_max', models.FloatField(blank=True, null=True, verbose_name='適正温度（上限 ℃）')),
                ('optimal_humidity_min', models.FloatField(blank=True, null=True, verbose_name='適正湿度（下限 %）')),
                ('optimal_humidity_max', models.FloatField(blank=True, null=True, verbose_name='適正湿度（上限 %）')),
                ('optimal_moisture_min', models.FloatField(blank=True, null=True, verbose_name='適正土壌水分（下限 %）')),
                ('optimal_moisture_max', models.FloatField(blank=True, null=True, verbose_name='適正土壌水分（上限 %）')),
                ('optimal_light_min', models.FloatField(blank=True, null=True, verbose_name='適正光量スコア（下限）')),
                ('optimal_light_max', models.FloatField(blank=True, null=True, verbose_name='適正光量スコア（上限）')),
                ('target_light_score', models.FloatField(default=30000.0, verbose_name='目標日照スコア（1日）')),
            ],
            options={
                'verbose_name': '植物マスタ',
                'verbose_name_plural': '植物マスタ',
                'db_table': 'plant_master',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, unique=True, verbose_name='デバイス名')),
                ('device_uuid', models.CharField(max_length=100, unique=True, verbose_name='デバイスUUID')),
                ('wifi_ssid', models.CharField(blank=True, max_length=100, verbose_name='Wi-Fi SSID')),
                ('interval_seconds', models.PositiveIntegerField(default=300, verbose_name='計測間隔（秒）')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dashboard.plant', verbose_name='観測対象の植物')),
            ],
            options={
                'verbose_name': 'デバイス',
                'verbose_name_plural': 'デバイス',
                'db_table': 'device',
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.plantmaster', verbose_name='植物種類'),
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(verbose_name='計測日時')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='受信日時')),
                ('soil_raw', models.IntegerField(blank=True, null=True, verbose_name='土壌水分(生)')),
                ('light_raw', models.IntegerField(blank=True, null=True, verbose_name='光量(生)')),
                ('moisture', models.FloatField(blank=True, null=True, verbose_name='土壌水分(%)')),
                ('light', models.FloatField(blank=True, null=True, verbose_name='光量スコア')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度(℃)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度(%)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.device', verbose_name='測定デバイス')),
            ],
            options={
                'verbose_name': 'センサーログ',
                'verbose_name_plural': 'センサーログ',
                'db_table': 'sensor_logs',
                'ordering': ['-measured_at'],
            },
        ),
    ]
