# Generated by Django 6.0.6 on 2026-07-17 01:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(default='新しい植物', max_length=100, verbose_name='植物名')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='栽培開始日')),
            ],
            options={
                'db_table': 'my_plant',
            },
        ),
        migrations.CreateModel(
            name='PlantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='種類名')),
                ('target_light_score', models.FloatField(default=30000.0, verbose_name='目標日照スコア(1日)')),
                ('optimal_temp_max', models.FloatField(blank=True, null=True, verbose_name='適正温度(上限)')),
                ('optimal_temp_min', models.FloatField(blank=True, null=True, verbose_name='適正温度(下限)')),
            ],
            options={
                'db_table': 'plant_master',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, unique=True, verbose_name='デバイス識別名')),
                ('interval_seconds', models.IntegerField(default=300, verbose_name='計測間隔(秒)')),
                ('my_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.myplant', verbose_name='観測対象の植物')),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.AddField(
            model_name='myplant',
            name='plant_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.plantmaster', verbose_name='ベースとなる植物種類'),
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='取得日時')),
                ('soil_raw', models.IntegerField(blank=True, null=True, verbose_name='土壌水分(生)')),
                ('light_raw', models.IntegerField(blank=True, null=True, verbose_name='光量(生)')),
                ('moisture', models.FloatField(blank=True, null=True, verbose_name='土壌水分(%)')),
                ('light', models.FloatField(blank=True, null=True, verbose_name='光量スコア(0-100)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度(℃)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度(%)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.device', verbose_name='測定デバイス')),
            ],
            options={
                'db_table': 'sensor_logs',
            },
        ),
    ]
