# Generated by Django 6.0.6 on 2026-07-21 14:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='計測日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 21, 14, 40, 36, 352268, tzinfo=datetime.timezone.utc), verbose_name='受信日時'),
        ),
    ]
