# Generated by Django 6.0.6 on 2026-07-22 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_sensorlog_timestamp_sensorlog_measured_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlog',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 22, 9, 14, 29, 284388, tzinfo=datetime.timezone.utc), verbose_name='受信日時'),
        ),
    ]
