# Generated by Django 6.0.6 on 2026-07-22 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_sensorlog_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlog',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 22, 9, 58, 39, 573000, tzinfo=datetime.timezone.utc), verbose_name='受信日時'),
        ),
    ]
