# Generated by Django 6.0.6 on 2026-07-22 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_sensorlog_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlog',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='受信日時'),
        ),
    ]
