; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



; PlatformIOプロジェクト全体の設定ファイル

; このファイルでは
; ・ボード
; ・ライブラリ
; ・コンパイル設定
; ・デバッグ設定
; を一か所で管理する

; esp32dev開発環境を使用する
[env:esp32dev]

; 使用するメーカーのSDK
platform = espressif32

; 使用するボード
board = esp32dev

; ESP32をArduino方式で開発する
framework = arduino

; 通信速度の設定
monitor_speed = 115200
; 上記は Serial.begin(115200); と必ず一致させる

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor